
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BestBuySC' do
    pod 'Alamofire', '~> 1.3.1'
	pod 'Loggerithm', '~> 1.2'
    pod 'SwiftyJSON', '~> 2.2.1'
    pod 'HanekeSwift', '~> 0.9.1'
    pod 'MBProgressHUD', '~> 0.9.1'
end

target 'BestBuySCTests' do

end
